---
  - name: loop in ansible
    hosts: web
    become: true
    tasks:
    - name: install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: installed #item is a reserved keyword
      loop:
        - nginx
        - zip
        - mysql