---
  - name: nginx installation
    hosts: web
    become: yes
    tasks:
    - name: install nginx server
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: start nginx server
      ansible.builtin.service:
        name: nginx
        state: started
        enbaled: yes

