---
  - name: varibale file
    hosts: local
    connection: local

    vars_files:
      - vars.yml

    tasks:
    - name: variable file usage
      ansible.builtin.debug:
        msg: "Trainer: {{ Trainer }}, Duration: {{ Duration }}, Timings: {{ Timings }}"
